### ISSUE TITLE
Final report

### ISSUE THREAD

**Issue by Boci0123** [Teaching-projects/SZE-MOSZE-2021-Signal#12]
@hegyhati Tisztelt Tanár Úr! Elkészültünk a féléves feladattal, legyenszíves értékelje.

**Comment by hegyhati** [comment]
Sziasztok! 

Hat sracok, ez 4 fore azert eleg minimalista egy projekt, bar cmake/cppchek/stb van. En most egy joszivunek mondhato 3-asnal tartok most. Ha ez nektek jo, akkro irom neptunba. Ha nem, akkor a negyesert azert kodmennyisegben ennek a (hasrautve) kb a duplajat azert bele kellene tenni.

**Comment by Boci0123** [comment]
Tisztelt Tanár úr!
Elfogadjuk a 3-ast.
Köszönjük szépen.

**Comment by hegyhati** [comment]
Megajanlottan beirtam, el tudjatok fogadni.
